version: "3"

tasks:
  build:
    cmds:
      - echo "Building ...."    
  generate:
    cmds:
      - protoc --go_out=./proto/gen --go_opt=paths=source_relative --go-grpc_out=./proto/gen --go-grpc_opt=paths=source_relative proto/payment.proto